# Generated by Django 3.0.8 on 2020-10-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201016_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
