# Generated by Django 3.0.8 on 2020-10-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201022_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
